name: Validate Workflow
on: push
jobs: 
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate html files
        run: test -f index.html

      - name: Validate js files
        run: test -f script.js

      - name: Validate js files
        run: node --check script.js

